version: '3.7'
services: 
    numbersservice:
        container_name: Numbers
        build: 
            context: ./numbers
            dockerfile: dockerfile
        ports: 
          - "7001:7001"
    wordsservice:
        container_name: Words
        build: 
            context: ./words
            dockerfile: dockerfile
        ports: 
          - "7002:7002"
networks: 
  default:
    name: kong-comic-net
